---
# vars file
# src https://github.com/89luca89/ansible-fedora-minimal/blob/master/roles/fedora_minimal/defaults/main.yml\

# repo baseurl, not including the "$basearch" at the end.
google_chrome__yum_baseurl: "https://dl.google.com/linux/chrome/rpm/stable/"

# kubelogin version
kubelogin_version: "v0.2.10"

# jira CLI version
jira_cli_version: "1.7.0"

# osdctl CLI version
osdctl_version: "0.49.0"

# ocm CLI version
ocm_cli_version: "1.0.8"

# backplane CLI version
backplane_cli_version: "0.6.2"

base_packages:
  - "@Development Tools"
  - "@Development Libraries"
  - azure-cli
  - ansible
  - bison
  - evolution
  - helm
  - libappindicator-gtk3
  - liberation-fonts
  - kernel-devel
  - kernel-headers
  - docker
  - clang
  - gcc
  - gcc-c++
  - pass
  - snapd
  - tmux
  - vim
  - virt-manager
  - krb5-workstation
  - libgnome
  - gimp
  - sshuttle
  - lm_sensors
  - vlc
  - rsync
  - kernel-headers
# Required for multi arch builds
  - qemu-user-static

codecs_packages:
  - ffmpeg
  - gstreamer1-libav
  - gstreamer1-plugins-base
  - gstreamer1-plugins-base-tools
  - gstreamer1-plugins-good
  - gstreamer1-plugins-good-extras
  - gstreamer1-plugins-ugly
  - gstreamer1-plugins-ugly-free
  - gstreamer1-svt-vp9
  - libva-devel
  - libva-utils
  - libva-vdpau-driver
  - libvdpau-va-gl
  - libavcodec-freeworld

