- name: Ensure azure CLI dir exists
  ansible.builtin.file:
    path: /home/jamesh/.azure
    state: directory
    mode: '0755'

- name: Set azure CLI configuration
  copy:
    src: azure_cli_config
    dest: /home/jamesh/.azure/config
    owner: jamesh
    group: jamesh
    mode: '1755'
  tags:
    - cloud-tools
    - azure
    - config
