---
# Create base laptop configuration
#

- name: Update packages
  dnf:
    name: "*"
    state: latest
  become: yes
  tags:
    - base
    - packages

- name: Build up base laptop
  import_tasks: fedora_laptop.yml
  tags:
    - base
    - packages

- name: External packages
  import_tasks: external_packages.yml
  tags:
    - applications
    - packages

- name: Setup repos
  import_tasks: config_repositories.yml
  tags:
    - repositories
    - config
