- name: Add repository VS Code Repostiory
  ansible.builtin.yum_repository:
    name: vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    description: Visual
    baseurl: https://packages.microsoft.com/yumrepos/vscode
  tags:
    - dev-tools
    - vscode
    - repos

- name: Update VS Code
  become: yes
  ansible.builtin.dnf:
    name: code
    state: latest
  tags:
    - applications
    - vscode
    - packages